# docker-compose.yml
version: '3'
services:
  app:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: vue-app
    ports:
      - 8080:80

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx-app
    # volumes:
    #   - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - app